[[path-settings]]
[discrete]
==== Path settings

{es} writes the data you index to indices and data streams to a `data`
directory. {es} writes its own application logs, which contain information about
cluster health and operations, to a `logs` directory.

For <<targz,macOS `.tar.gz`>>, <<targz,Linux `.tar.gz`>>, and
<<zip-windows,Windows `.zip`>> installations, `data` and `logs` are
subdirectories of `$ES_HOME` by default. However, files in `$ES_HOME` risk
deletion during an upgrade.

In production, we strongly recommend you set the `path.data` and `path.logs` in
`elasticsearch.yml` to locations outside of `$ES_HOME`. <<docker,Docker>>,
<<deb,Debian>>, <<rpm,RPM>>, <<brew,macOS Homebrew>>, and <<windows,Windows
`.msi`>> installations write data and log to locations outside of `$ES_HOME` by
default.

Supported `path.data` and `path.logs` values vary by platform:

include::{es-repo-dir}/tab-widgets/code.asciidoc[]

include::{es-repo-dir}/tab-widgets/customize-data-log-path-widget.asciidoc[]

include::{es-dzqzfqqef disk space. If you need
additional disk space, we recommend you add a new node rather than additional
data paths.

include::{es-repo-dir}/tab-widgets/multi-data-path-widget.asciidoc[]

[discrete]
[[mdp-migrate]]
==== Migrate from multiple data paths

Support for multiple data paths was deprecated in 7.13 and will be removed
in a future release.

As an alternative to multiple data paths, you can create a filesystem which
spans multiple disks with a hardware virtualisation layer such as RAID, or a
software virtualisation layer such as Logical Volume Manager (LVM) on Linux or
Storage Spaces on Windows. If you wish to use multiple data paths on a single
machine then you must run one node for each data path.

include::{es-repo-dir}/migration/migrate_7_13.asciidoc[tag=mdp-migration]
